<div class="row">
  <div class="col-sm">
    <?php if($this->totalItemCount<=0): ?>
    <div>Showing 0 entries</div>
    <?php else: ?>
    <?php $temp = $this->current * $this->itemCountPerPage; ?>
    <div>Showing <?php echo (($temp) - $this->itemCountPerPage) + 1 ; ?> to <?php echo ($this->totalItemCount < $temp) ? $this->totalItemCount : $temp; ?> of <?php echo $this->totalItemCount; ?> <?php echo $this->totalItemCount<=1 ? 'entry' : 'entries'; ?></div>
    <?php endif; ?>
  </div>
  <div class="col-sm">
    <div class="float-right">
      <!-- Pagination -->
      <?php if ($this->pageCount): ?>
      <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
          <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, ['page' => $this->previous]); ?>">
            &lt; Previous
          </a></li>
        <?php else: ?>
          <li class="page-item disabled"><span class="page-link">&lt; Previous</span></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != $this->current): ?>
            <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, ['page' => $page]); ?>">
                <?= $page; ?>
            </a></li>
          <?php else: ?>
            <li class="page-item disabled"><span class="page-link"><?= $page; ?></span></li>
          <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
          <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, ['page' => $this->next]); ?>">
            Next &gt;
          </a></li>
        <?php else: ?>
          <li class="page-item disabled"><span class="page-link">Next &gt;</span></li>
        <?php endif; ?>
      </ul>
      <?php endif; ?>
    </div>
  </div>
</div>
