<div class="container space-top-md-2">
  <!-- Page Heading/Breadcrumbs -->
  <h1 class="mt-4 mb-3">Welcome
    <small><?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></small>
  </h1>

  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<?php echo $this->url('member'); ?>">Home</a>
    </li>
    <li class="breadcrumb-item active">Dashboard</li>
  </ol>

  <!-- Content Row -->
  <div class="row">

    <!-- Sidebar Column -->
    <div class="col-lg-3 mb-4">
      <?php echo $this->partial('partial/member/menu.phtml', array(
          'route' => $this->route,
          'action' => $this->action,
      )); ?>
    </div>

    <!-- Content Column -->
    <div class="col-lg-9 mb-4">
      <?php
      $flash = $this->flashMessenger();
      $flash->setMessageOpenFormat('<div%s role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          ')
          ->setMessageSeparatorString('')
          ->setMessageCloseString('</div>');

      echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
      echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
      echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
      echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
       ?>
       <div class="row mb-4">
         <div class="col-md-8">
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
         </div>
         <div class="col-md-4">
           <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('project', ['action' => 'create']); ?>">Create Project</a>
         </div>
       </div>

       <div class="card">
        <div class="card-header">
          Projects
        </div>
        <div class="card-body">
          <?php if(count($paginator) > 0): ?>

              <?php
                          echo $this->paginationControl(
                              $this->paginator,
                              'sliding',
                              "partial/project/paginator.phtml",
                              array(
                                'route' => 'projects',
                                'search_by' => $this->search_by,
                              )
                          );
                        ?>

              <div class="row">
                <?php foreach ($paginator as $row): ?>
                <div class="col-lg-4 col-sm-6 portfolio-item">
                  <div class="card h-100">
                    <a href="#"><img class="card-img-top" src="/img/project/<?php echo $row->getId(); ?>/photo-700x400.jpg" alt=""></a>
                    <div class="card-body">
                      <h4 class="card-title">
                        <a href="#"><?php echo $this->escapehtml($row->getName()); ?></a>
                      </h4>
                      <p class="card-text"><?php echo $this->escapehtml($row->getDescription()); ?></p>
                      <div class="row mb-1">
                          <div class="col-6">
                            <h4 class="small text-muted">
                              Goal: <strong class="text-secondary">ETH <?php echo $this->escapehtml($row->getMinimumContribution()); ?></strong>
                            </h4>
                            <div class="js-hr-progress progress" style="height: 6px;">
                              <div class="js-hr-progress-bar progress-bar bg-success" role="progressbar" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                          </div>
                          <div class="col-6">
                            <h4 class="small text-muted">
                              Contributors: <strong class="text-secondary">0</strong>
                            </h4>
                            <div class="js-hr-progress progress" style="height: 6px;">
                              <div class="js-hr-progress-bar progress-bar bg-warning" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                          </div>
                        </div>
                    </div>
                    <div class="card-footer">
                      <a href="#" class="btn btn-primary">View Details</a>
                    </div>
                  </div>
                </div>
                <?php endforeach; ?>
              </div>


              <?php
                          echo $this->paginationControl(
                              $this->paginator,
                              'sliding',
                              "partial/project/paginator.phtml",
                              array(
                                'route' => 'projects',
                                'search_by' => $this->search_by,
                              )
                          );
                        ?>
         <?php else: ?>
           <div class="alert alert-warning" role="alert">
           No Project Started
         </div>
           <?php endif; ?>
        </div>
      </div>


    </div>
    <!-- /.container-fluid -->

    </div>
  </div>
  <!-- /.row -->
</div>
