<div class="container space-top-md-2">
  <!-- Login Form -->
    <div class="container space-2">
      <!-- Page Heading/Breadcrumbs -->
      <h1><?php echo $this->escapehtml($this->project->getName()); ?></h1>

      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="<?php echo $this->url('member'); ?>">Home</a>
        </li>
        <li class="breadcrumb-item active">Project</li>
      </ol>

      <div class="row">
        <div class="col-lg-8">
          <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>');

            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
             ?>
          <small><strong>Contract Address:</strong> <?php echo $this->escapehtml($this->project->getContractAddress()); ?> </small>
          <hr>
          <div class="text-center">
            <img class="img-fluid rounded" src="/img/project/<?php echo $this->project->getId(); ?>/photo_480x320.jpg" alt="">
          </div>
          <hr>
          <p><?php echo $this->escapehtml($this->project->getDescription()); ?></p>
          <hr>

          <div class="row">
            <div class="col-lg-6">
              <div class="card">
                <div class="card-header" style="background-color:#ffc107;color:#fff">
                  Project Balance
                </div>
                <div class="card-body">
                  <h5 class="card-title"><?php echo number_format($this->projectBalance, 8); ?> ETH</h5>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="card">
                <div class="card-header" style="background-color:#17a2b8;color:#fff">
                  Minimum Contribution
                </div>
                <div class="card-body">
                  <h5 class="card-title"><?php echo number_format($this->project->getMinimumContribution(), 8); ?> ETH</h5>
                </div>
              </div>
            </div>
          </div>
          <br>
          <?php
          $projectAttributes = $this->getProjectAttributes($this->project->getContractAddress(), $this->user->getPublicAddress());

          ?>
          <div class="row">
            <div class="col-lg-6">
              <div class="card">
                <div class="card-header" style="background-color:#697179;color:#fff">
                  Milestones
                </div>
                <div class="card-body">
                  <h5 class="card-title"><?php echo $projectAttributes['milestonesCount']; ?></h5>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="card">
                <div class="card-header" style="background-color:#28a745;color:#fff">
                  Contributors
                </div>
                <div class="card-body">
                  <h5 class="card-title"><?php echo $projectAttributes['contributorsCount']; ?></h5>
                </div>
              </div>
            </div>
          </div>
          <br>

          <hr>
          <div class="card">
            <div class="card-header">
              Milestones
            </div>
            <div class="card-body">
              <table class="table table-sm table-hover table-bordered table-striped">
                <thead>
                  <tr>
                      <th scope="col"></th>
                    <th width="20%" scope="col">Date</th>
                    <th scope="col">Milestone</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($milestones as $milestone): ?>
                  <tr>
                    <td align="center">
                      <?php if($milestone['milestone_type']=='general'): ?><i class="fas fa-user-tie"></i><?php else: ?><i class="fas fa-truck"></i><?php endif; ?>

                    </td>
                    <td><?php echo date('M d, Y', $milestone['time']); ?></td>
                    <td><?php echo $milestone['description']; ?></td>
                  </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
          <!-- Side Widget -->
          <?php if ($user = $this->identity()): ?>
            <?php if ($this->projectOwner->getPublicAddress() != $this->user->getPublicAddress()): ?>
              <div class="card">
                <h5 class="card-header">My Balance: ETH <?php echo number_format($this->userBalance, 8); ?></h5>
                <div class="card-body text-center">
                  <strong>My Address</strong>
                  <input type="text" class="form-control" value="<?php echo $this->escapehtml($this->user->getPublicAddress()); ?>">
                  <img class="img-fluid" src="<?php echo $this->getQRCode($this->user->getPublicAddress(), 200, 200); ?>">
                </div>
              </div>
              <br>
              <div class="card">
                <h5 class="card-header">Contribute to this project!</h5>
                <div class="card-body">


                  <?php if($userBalance >= $this->project->getMinimumContribution()): ?>
                  <small>
                    I agree to the
                    <a class="link-muted" href="#">Terms and Conditions</a>
                  </small>
                  <form method="post" action="<?php echo $this->url('project', array('action' => 'view', 'id' => $this->project->getContractAddress(),)); ?>">
                    <input type="hidden" name="action" value="invest">
                    <div class="form-row align-items-center">
                      <div class="col-sm-12 my-1">
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <div class="input-group-text">ETH</div>
                          </div>
                          <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Amount" name="amount" value="<?php echo $this->project->getMinimumContribution() + '0.0000000000021'; ?>">
                        </div>
                      </div>
                      <div class="col-auto my-1">
                        <button type="submit" class="btn btn-success">Contribute</button>
                      </div>
                    </div>
                  </form>
                  <?php else: ?>
                    <p>Not enough balance!</p>
                  <?php endif; ?>
                </div>
            <?php else: ?>
              <div class="card">
                <h5 class="card-header">Add Milestone</h5>
                <div class="card-body">
                  <form method="post" action="<?php echo $this->url('project', array('action' => 'view', 'id' => $this->project->getContractAddress(),)); ?>">
                      <input type="hidden" name="action" value="milestone">
                    <div class="form-group">
                      <label>Type</label>
                      <select class="form-control" name="milestone_type" id="milestone_type" required>
                        <option value="general">General</option>
                        <option value="purchase_order">Purchase Order</option>
                      </select>
                    </div>
                    <div class="form-group supplier_wrapper">
                      <label>Supplier</label>
                      <select class="form-control" name="supplier_id" id="supplier_id">
                        <option value="">Select Supplier</option>
                        <?php foreach ($this->suppliers as $row): ?>
                          <option value="<?php echo $this->escapehtml($row->getId()); ?>"><?php echo $this->escapehtml($row->getName()); ?> (<?php echo $this->escapehtml($row->getPublicAddress()); ?>)</option>
                        <?php endforeach; ?>
                      </select>
                    </div>
                    <div class="form-group supplier_wrapper">
                      <label>Amount</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">ETH</div>
                        </div>
                        <input type="text" class="form-control" placeholder="Amount" id="amount" name="amount" value="">
                      </div>
                    </div>
                    <div class="form-group supplier_wrapper">
                      <label>Date expected</label>
                      <input type="text" class="form-control" id="date_expected" name="date_expected" value="">
                    </div>
                    <div class="form-group">
                      <label>Description</label>
                      <textarea class="form-control" name="description" id="description" rows="3" required></textarea>
                      (Character Count: <span id="description_count">0</span>)
                    </div>
                    <div class="form-group">
                      <label>Comments</label>
                      <textarea class="form-control" name="comments" id="comments" rows="3"></textarea>
                      (Character Count: <span id="comments_count">0</span>)
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                  <script>
                  $(document).ready(function(){
                    $("#milestone_type").change(function() {
                      if($(this).val() == 'purchase_order'){
                        $(".supplier_wrapper").show();
                      }else{
                        $(".supplier_wrapper").hide();
                      }
                    });
                    $(".supplier_wrapper").hide();

                    $("#description").on("input", function() {
                      $("#description_count").text(this.value.length);
                    });
                    $("#comments").on("input", function() {
                      $("#comments_count").text(this.value.length);
                    });
                    $("#date_expected").datepicker({
                      dateFormat:"yy-mm-dd",
                    });
                  });
                  </script>
                </div>
              </div>
            <?php endif; ?>
          <?php endif; ?>

          </div>
        </div>

      </div>
      <!-- /.row -->
    </div>
  <!-- End Login Form -->
</div>
