<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">About
  <small>Subheading</small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="index.html">Home</a>
  </li>
  <li class="breadcrumb-item active">About</li>
</ol>

<h2>Our Supppliers</h2>

<div class="row mb-4">
  <div class="col-md-8">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
  </div>
  <div class="col-md-4">
    <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('project', ['action' => 'create',]); ?>">Register As Supplier</a>
  </div>
</div>

<div class="row">
  
  <div class="col-lg-4 mb-4">
    <div class="card h-100 text-center">
      <img class="card-img-top" src="http://placehold.it/750x450" alt="">
      <div class="card-body">
        <h4 class="card-title">Team Member</h4>
        <h6 class="card-subtitle mb-2 text-muted">Position</h6>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus aut mollitia eum ipsum fugiat odio officiis odit.</p>
      </div>
      <div class="card-footer">
        <a href="#">name@example.com</a>
      </div>
    </div>
  </div>

</div>
<!-- /.row -->
