<!-- Login Form -->
    <div class="container space-2">
      <h1>Become a <span class="font-weight-semi-bold">supplier</span></h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-primary breadcrumb-white">
          <li class="breadcrumb-item">
            <a class="breadcrumb-link" href="<?php echo $this->url('home'); ?>">Home</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Supplier</li>
        </ol>
      </nav>

      <div class="row">
        <div class="col-lg-8">
          <?php
            $form->setAttribute('action', $this->url('supplier'));
            $form->setAttribute('class', 'js-validate');
            $form->setAttribute('id', 'myForm');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <?php
              $flash = $this->flashMessenger();
              $flash->setMessageOpenFormat('<div%s role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  ')
                  ->setMessageSeparatorString('')
                  ->setMessageCloseString('</div>');

              echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
              echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
              echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
              echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
               ?>

            <!-- Form Group -->
            <div class="js-form-message form-group">
              <?= $this->formLabel($form->get('name')) ?>
              <?= $this->formElement($form->get('name')) ?>
              <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'help-block']) ?>
            </div>
            <!-- End Form Group -->

            <!-- Form Group -->
            <div class="js-form-message form-group">
              <?= $this->formLabel($form->get('description')) ?>
                <div class="input-group">
                <?= $this->formElement($form->get('description')) ?>
                </div>
                <?= $this->formElementErrors()->render($form->get('description'), ['class' => 'help-block']) ?>
            </div>
            <!-- End Form Group -->

          <div class="js-form-message form-group">
              <?= $this->formLabel($form->get('mayors_permit')) ?>
              <?= $this->formFile($form->get('mayors_permit')) ?>
              <?= $this->formElementErrors()->render($form->get('mayors_permit'), ['class' => 'help-block']) ?>
              <ul class="help-block">
                <li>File Types: jpg, jpeg, png</li>
              </ul>
            </div>

            <div class="js-form-message form-group">
                <?= $this->formLabel($form->get('bir_certificate')) ?>
                <?= $this->formFile($form->get('bir_certificate')) ?>
                <?= $this->formElementErrors()->render($form->get('bir_certificate'), ['class' => 'help-block']) ?>
                <ul class="help-block">
                  <li>File Types: jpg, jpeg, png</li>
                </ul>
              </div>

            <!-- Checkbox -->
            <div class="js-form-message mb-5">
              <div class="custom-control custom-checkbox d-flex align-items-center text-muted">
                <input type="checkbox" class="custom-control-input" id="termsCheckbox" name="termsCheckbox" required
                       data-msg="Please accept our Terms and Conditions."
                       data-error-class="u-has-error"
                       data-success-class="u-has-success">
                <label class="custom-control-label" for="termsCheckbox">
                  <small>
                    I agree to the
                    <a class="link-muted" href="#">Terms and Conditions</a>
                  </small>
                </label>
              </div>
            </div>
            <!-- End Checkbox -->

            <!-- Button -->
            <div class="row align-items-center mb-5">
              <div class="col-12">
                <button id="myButton" type="submit" class="btn btn-primary transition-3d-hover">Submit</button>
              </div>
            </div>
            <!-- End Button -->
          <?php echo $this->form()->closeTag();?>
        <!-- End Login Form -->
        </div>

        <div class="col-md-4">
          <div class="card my-4">
            <h5 class="card-header">Requirements</h5>
            <div class="card-body">
              <p>BIR Certificate</p>
              <small>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>
              <img class="img-fluid" src="/img/bir-certificate.jpg">
              <br><br>
              <p>Mayor'S Permit</p>
              <small>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>
              <img class="img-fluid" src="/img/mayors-permit.jpg">
            </div>
          </div>
        </div>

      </div>

      <script>
      $(document).ready(function(){
        $("#myButton").click(function() {
          return signin();
        });
        $("#myForm").submit(function() {
          return signin();
        });
      });
      </script>
