<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Welcome
  <small>
    <?php if ($this->user->getRole() == 'doctor'): ?>
      <?php if($this->user->getGender() == 'f'): ?>
      Dra.
    <?php else: ?>
      Dr.
    <?php endif; ?><?php endif; ?>
    <?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('member'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Dashboard</li>
</ol>

<!-- Content Row -->
<div class="row">

  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <?php echo $this->partial('partial/member/menu.phtml', array(
        'route' => $this->route,
        'action' => $this->action,
    )); ?>
  </div>

  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>
        <h2>My Medical Records</h2>

        <div class="float-right">
          <a class="btn btn-secondary" href="<?php echo $this->url('member', ['action' => 'medical-record-add']); ?>">Add Medical Record</a>
        </div>
        <div class="clearfix"></div><br>


        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Search/Filter</h6>
          </div>
          <div class="card-body">

            <form method="post">
              <div class="form-row">
                <div class="form-group col-md-5">
                  <input type="email" class="form-control" id="inputEmail4" placeholder="%Keyword%">
                </div>
                <div class="form-group col-md-1">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>


            </form>
          </div>
        </div>

        <div class="card shadow mb-4">
          <div class="card-body">

            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Name</th>
                  <th scope="col">View</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Jun 29, 2019</th>
                  <td>Chest Pain</td>
                  <td><a href="#">View</a></td>
                </tr>
              </tbody>
            </table>

          </div>
        </div>



  </div>
  <!-- /.container-fluid -->

  </div>
</div>
<!-- /.row -->
