<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Welcome
  <small>
    <?php if ($this->user->getRole() == 'doctor'): ?>
      <?php if($this->user->getGender() == 'f'): ?>
      Dra.
    <?php else: ?>
      Dr.
    <?php endif; ?><?php endif; ?>
    <?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('member'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Dashboard</li>
</ol>

<!-- Content Row -->
<div class="row">

  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <?php echo $this->partial('partial/member/menu.phtml', array(
        'route' => $this->route,
        'action' => $this->action,
    )); ?>
  </div>

  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <h2>Edit Medical Record</h2>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>

     <div class="card shadow mb-4">
       <div class="card-body">
         <?php
         $form->prepare();
         echo $this->form()->openTag($form);
         ?>

         <img src="/img/medical-record/<?php echo $this->medicalRecord->getId(); ?>/photo-750x450.jpg" class="img-fluid" alt="Responsive image">

         <hr>

         <div class="form-group">
               <div class="form-group">
                 <?= $this->formLabel($form->get('name')) ?>
                 <?= $this->formElement($form->get('name')) ?>
                 <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'help-block']) ?>
               </div>
         </div>
         <div class="form-group">
               <div class="form-group">
                 <?= $this->formLabel($form->get('description')) ?>
                 <?= $this->formElement($form->get('description')) ?>
                 <?= $this->formElementErrors()->render($form->get('description'), ['class' => 'help-block']) ?>
               </div>
         </div>
         <div class="form-group">
               <div class="form-group">
                 <?= $this->formLabel($form->get('tags')) ?>
                 <?= $this->formElement($form->get('tags')) ?>
                 <?= $this->formElementErrors()->render($form->get('tags'), ['class' => 'help-block']) ?>
               </div>
         </div>
         <div class="form-group">
               <div class="form-group">
                 <?= $this->formLabel($form->get('request_by')) ?>
                 <?= $this->formElement($form->get('request_by')) ?>
                 <?= $this->formElementErrors()->render($form->get('request_by'), ['class' => 'help-block']) ?>
               </div>
         </div>
         <div class="form-group">
               <div class="form-group">
                 <?= $this->formLabel($form->get('hospital')) ?>
                 <?= $this->formElement($form->get('hospital')) ?>
                 <?= $this->formElementErrors()->render($form->get('hospital'), ['class' => 'help-block']) ?>
               </div>
         </div>
         <?php echo $this->formSubmit($form->get('submit')); ?>
         <?php echo $this->form()->closeTag();?>
        </div>
      </div>
  </div>
  <!-- /.container-fluid -->

  </div>
</div>
<!-- /.row -->

<script type="text/javascript">
	$('#tags').tagsInput();
</script>
