<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Welcome
  <small>
    <?php if ($this->user->getRole() == 'doctor'): ?>
      <?php if($this->user->getGender() == 'f'): ?>
      Dra.
    <?php else: ?>
      Dr.
    <?php endif; ?><?php endif; ?>
    <?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('member'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Pharmaceutical Products</li>
</ol>

<!-- Content Row -->
<div class="row">

  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <?php echo $this->partial('partial/member/menu.phtml', array(
        'route' => $this->route,
        'action' => $this->action,
    )); ?>
  </div>

  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>
     <div class="card shadow mb-4">
       <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary">Search/Filter</h6>
       </div>
       <div class="card-body">
               <form method="post">
                 <div class="form-row">
                   <div class="form-group col-md-3">
                     <input type="email" class="form-control" id="inputEmail4" placeholder="%Name%">
                   </div>
                   <div class="form-group col-md-3">
                     <select class="form-control" name="cities" id="cities">
                       <option value="">All Categories</option>
                         <option value="">Gastroenterologist</option>
                         <option value="">General Pediatrics</option>
                           <option value="">Oncologist</option>
                           <option value="">Opthalmologist</option>
                           <option value="">Pediatrics</option>

               </select>




                   </div>
                   <div class="form-group col-md-1">
                     <button type="submit" class="btn btn-primary">Submit</button>
                   </div>
                 </div>


               </form>
               </div>
               </div>


                 <div class="card shadow mb-4">
                   <div class="card-body">

                     <div class="row">
                       <?php foreach ($paginator as $row): ?>
                       <div class="col-lg-4 mb-4">
                         <div class="card h-100 text-center">
                           <img class="card-img-top" src="/img/medicine/<?php echo $row->getId(); ?>/photo-750x450.jpg" alt="">
                           <div class="card-body">
                             <h4 class="card-title"><?php echo $this->escapeHtml($row->getName()); ?></h4>
                             <p><?php echo $this->escapeHtml($row->getDescription()); ?></p>
                             <h6 class="card-subtitle mb-2 text-muted">₱<?php echo $this->escapeHtml($row->getPrice()); ?></h6>
                           </div>
                           <div class="card-footer">
                             <a class="btn btn-primary" href="#">Buy Now</a>
                           </div>
                         </div>
                       </div>
                       <?php endforeach; ?>
                     </div>

                   </div>
                 </div>

  </div>
  <!-- /.container-fluid -->


  </div>
</div>
<!-- /.row -->
