<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Welcome
  <small>
    <?php if ($this->user->getRole() == 'doctor'): ?>
      <?php if($this->user->getGender() == 'f'): ?>
      Dra.
    <?php else: ?>
      Dr.
    <?php endif; ?><?php endif; ?>
    <?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('member'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Checkup/Consultations</li>
</ol>

<!-- Content Row -->
<div class="row">
  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <?php echo $this->partial('partial/member/menu.phtml', array(
        'route' => $this->route,
        'action' => $this->action,
    )); ?>
  </div>
  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <?php if ($this->user->getRole() == 'patient'): ?>
    <h2>Checkup/Consultations</h2>
  <?php else: ?>
    <h2>Patient on queue</h2>
  <?php endif; ?>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, et temporibus, facere perferendis veniam beatae non debitis, numquam blanditiis necessitatibus vel mollitia dolorum laudantium, voluptate dolores iure maxime ducimus fugit.</p>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?><div class="row">
      <div class="col-lg-12 mb-12">
        <?php if ($this->user->getRole() == 'patient'): ?>
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Search/Filter</h6>
          </div>
          <div class="card-body">

            <form method="post">
              <div class="form-row">
                <div class="form-group col-md-3">
                  <input type="email" class="form-control" id="inputEmail4" placeholder="%Name%">
                </div>
                <div class="form-group col-md-3">
                  <select class="form-control" name="cities" id="cities">
                    <option value="">All Cities</option>
	<option value="Caloocan">Caloocan</option>
	<option value="Las Piñas">Las Piñas</option>
	<option value="Makati ">Makati </option>
	<option value="Malabon">Malabon</option>
	<option value="Mandaluyong">Mandaluyong</option>
	<option value="Manila">Manila</option>
	<option value="Marikina">Marikina</option>
	<option value="Muntinlupa">Muntinlupa</option>
	<option value="Navotas">Navotas</option>
	<option value="Parañaque">Parañaque</option>
	<option value="Pasay">Pasay</option>
	<option value="Pasig ">Pasig </option>
	<option value="Quezon City">Quezon City</option>
	<option value="San Juan">San Juan</option>
	<option value="Taguig">Taguig</option>
	<option value="Valenzuela">Valenzuela</option>
	<option value="Butuan">Butuan</option>
	<option value="Cabadbaran">Cabadbaran</option>
	<option value="Bayugan">Bayugan</option>
	<option value="Legazpi">Legazpi</option>
	<option value="Ligao">Ligao</option>
	<option value="Tabaco">Tabaco</option>
	<option value="Isabela">Isabela</option>
	<option value="Lamitan">Lamitan</option>
	<option value="Balanga">Balanga</option>
	<option value="Batangas City">Batangas City</option>
	<option value="Lipa">Lipa</option>
	<option value="Tanauan">Tanauan</option>
	<option value="Baguio">Baguio</option>
	<option value="Tagbilaran">Tagbilaran</option>
	<option value="Malaybalay">Malaybalay</option>
	<option value="Valencia">Valencia</option>
	<option value="Malolos">Malolos</option>
	<option value="Meycauayan">Meycauayan</option>
	<option value="San Jose del Monte">San Jose del Monte</option>
	<option value="Tuguegarao">Tuguegarao</option>
	<option value="Iriga">Iriga</option>
	<option value="Naga">Naga</option>
	<option value="Roxas">Roxas</option>
	<option value="Bacoor">Bacoor</option>
	<option value="Cavite City">Cavite City</option>
	<option value="Dasmariñas">Dasmariñas</option>
	<option value="Imus">Imus</option>
	<option value="Tagaytay">Tagaytay</option>
	<option value="Trece Martires">Trece Martires</option>
	<option value="Bogo">Bogo</option>
	<option value="Carcar">Carcar</option>
	<option value="Cebu City">Cebu City</option>
	<option value="Danao">Danao</option>
	<option value="Lapu-Lapu">Lapu-Lapu</option>
	<option value="Mandaue">Mandaue</option>
	<option value="Naga">Naga</option>
	<option value="Talisay">Talisay</option>
	<option value="Toledo">Toledo</option>
	<option value="Kidapawan">Kidapawan</option>
	<option value="Panabo">Panabo</option>
	<option value="Samal">Samal</option>
	<option value="Tagum">Tagum</option>
	<option value="Davao City">Davao City</option>
	<option value="Digos">Digos</option>
	<option value="Mati">Mati</option>
	<option value="Borongan">Borongan</option>
	<option value="Batac">Batac</option>
	<option value="Laoag">Laoag</option>
	<option value="Candon">Candon</option>
	<option value="Vigan">Vigan</option>
	<option value="Iloilo City">Iloilo City</option>
	<option value="Passi">Passi</option>
	<option value="Cauayan">Cauayan</option>
	<option value="Ilagan">Ilagan</option>
	<option value="Santiago">Santiago</option>
	<option value="Tabuk">Tabuk</option>
	<option value="San Fernando">San Fernando</option>
	<option value="Biñan">Biñan</option>
	<option value="Cabuyao">Cabuyao</option>
	<option value="Calamba">Calamba</option>
	<option value="San Pablo">San Pablo</option>
	<option value="Santa Rosa">Santa Rosa</option>
	<option value="San Pedro">San Pedro</option>
	<option value="Iligan">Iligan</option>
	<option value="Marawi">Marawi</option>
	<option value="Baybay">Baybay</option>
	<option value="Ormoc">Ormoc</option>
	<option value="Tacloban">Tacloban</option>
	<option value="Cotabato City">Cotabato City</option>
	<option value="Masbate City">Masbate City</option>
	<option value="Oroquieta">Oroquieta</option>
	<option value="Ozamiz">Ozamiz</option>
	<option value="Tangub">Tangub</option>
	<option value="Cagayan de Oro">Cagayan de Oro</option>
	<option value="El Salvador">El Salvador</option>
	<option value="Gingoog">Gingoog</option>
	<option value="Bacolod">Bacolod</option>
	<option value="Bago">Bago</option>
	<option value="Cadiz">Cadiz</option>
	<option value="Escalante">Escalante</option>
	<option value="Himamaylan">Himamaylan</option>
	<option value="Kabankalan">Kabankalan</option>
	<option value="La Carlota">La Carlota</option>
	<option value="Sagay">Sagay</option>
	<option value="San Carlos">San Carlos</option>
	<option value="Silay">Silay</option>
	<option value="Sipalay">Sipalay</option>
	<option value="Talisay">Talisay</option>
	<option value="Victorias">Victorias</option>
	<option value="Bais">Bais</option>
	<option value="Bayawan">Bayawan</option>
	<option value="Canlaon">Canlaon</option>
	<option value="Dumaguete">Dumaguete</option>
	<option value="Guihulngan">Guihulngan</option>
	<option value="Tanjay">Tanjay</option>
	<option value="Cabanatuan">Cabanatuan</option>
	<option value="Gapan">Gapan</option>
	<option value="Muñoz">Muñoz</option>
	<option value="Palayan">Palayan</option>
	<option value="San Jose">San Jose</option>
	<option value="Calapan	Oriental">Calapan	Oriental</option>
	<option value="Puerto Princesa">Puerto Princesa</option>
	<option value="Angeles">Angeles</option>
	<option value="Mabalacat ">Mabalacat </option>
	<option value="San Fernando">San Fernando</option>
	<option value="Alaminos">Alaminos</option>
	<option value="Dagupan">Dagupan</option>
	<option value="San Carlos">San Carlos</option>
	<option value="Urdaneta">Urdaneta</option>
	<option value="Lucena">Lucena</option>
	<option value="Tayabas">Tayabas</option>
	<option value="Antipolo">Antipolo</option>
	<option value="Calbayog">Calbayog</option>
	<option value="Catbalogan">Catbalogan</option>
	<option value="Sorsogon City">Sorsogon City</option>
	<option value="General Santos">General Santos</option>
	<option value="Koronadal">Koronadal</option>
	<option value="Maasin">Maasin</option>
	<option value="Tacurong">Tacurong</option>
	<option value="Surigao City">Surigao City</option>
	<option value="Bislig">Bislig</option>
	<option value="Tandag">Tandag</option>
	<option value="Tarlac City">Tarlac City</option>
	<option value="Olongapo">Olongapo</option>
	<option value="Dapitan">Dapitan</option>
	<option value="Dipolog">Dipolog</option>
	<option value="Pagadian">Pagadian</option>
	<option value="Zamboanga City">Zamboanga City</option>
</select>
                </div>
                <div class="form-group col-md-3">
                  <select class="form-control" name="cities" id="cities">
                    <option value="">All Speclist</option>
                      <option value="">Gastroenterologist</option>
                      <option value="">General Pediatrics</option>
                        <option value="">Oncologist</option>
                        <option value="">Opthalmologist</option>
                        <option value="">Pediatrics</option>

</select>




                </div>
                <div class="form-group col-md-1">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>


            </form>
          </div>
        </div>

      </div>
    </div>
    <?php endif; ?>

    <div class="card shadow mb-4">
      <div class="card-body">

        <div class="row">
          <?php foreach ($paginator as $row): ?>
          <div class="col-lg-4 mb-4">
            <div class="card h-100 text-center">
              <img class="card-img-top" src="/img/user/<?php echo $row->getId(); ?>/photo-750x450.jpg" alt="">
              <div class="card-body">
                <h4 class="card-title">
                  <?php if ($this->user->getRole() == 'patient'): ?>
                  <?php if($row->getGender() == 'f'): ?>
                    Dra.
                  <?php else: ?>
                    Dr.
                  <?php endif; ?>
                  <?php endif; ?>
                  <?php echo $this->escapeHtml($row->getFirstName()); ?> <?php echo $this->escapeHtml($row->getLastName()); ?></h4>

                <h6 class="card-subtitle mb-2 text-muted"><?php if ($this->user->getRole() == 'patient'): ?><?php echo $this->escapeHtml($row->getTitle()); ?><?php endif; ?> <?php if($row->getId() == 3 || $row->getId() == 4 || $row->getId() == 8): ?><span class="online">Online</span><?php else: ?><span class="offline">Offline</span><?php endif; ?></h6>
              </div>
              <div class="card-footer">
                <a class="btn btn-primary" href="<?php echo $this->url('member', array('action' => 'video', 'id' => $row->getId(),)); ?>"><i class="fas fa-video"></i> <?php if ($this->user->getRole() == 'patient'): ?>Checkup<?php else: ?>Accept<?php endif; ?></a>
              </div>
            </div>
          </div>
          <?php endforeach; ?>
        </div>

      </div>
    </div>




  </div>
  <!-- /.container-fluid -->


  </div>
</div>
<!-- /.row -->

<script type="text/javascript">
(function blink() {
  $('.online').fadeOut(500).fadeIn(500, blink);

})();
</script>
