<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Welcome
  <small>
    <?php if ($this->user->getRole() == 'doctor'): ?>
      <?php if($this->user->getGender() == 'f'): ?>
      Dra.
    <?php else: ?>
      Dr.
    <?php endif; ?><?php endif; ?>
    <?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('member'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Dashboard</li>
</ol>

<!-- Content Row -->
<div class="row">

  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <?php echo $this->partial('partial/member/menu.phtml', array(
        'route' => $this->route,
        'action' => $this->action,
    )); ?>
  </div>

  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>

    <h2>Pay Using Tagcash</h2>

    <div class="card shadow mb-4">
      <div class="card-body">
        <form method="POST">
          <img class="img-fluid" src="/img/tagcash.png" style="width:200px;">
          <div class="form-group">
            <label for="email">Wallet:</label>
            <select name="wallet" class="form-control" id="sel1" required>
              <option value="1" selected>PHP</option>
              <option value="7">TAG</option>
            </select>
          </div>
          <div class="form-group">
            <label for="pwd">Amount:</label>
            <input type="text" class="form-control" name="amount" id="amount" value="1000.00" required>
          </div>
          <div class="form-group">
            <label for="pwd">Email/User Id:</label>
            <input type="text" class="form-control" name="email" id="email" required>
          </div>
          <div class="form-group">
            <label for="pwd">Pin:</label>
            <input type="text" class="form-control" name="pin" id="email" required>
          </div>
          <button type="submit" class="btn btn-primary">Pay Now</button>
        </form>


      </div>
    </div>




  </div>
  <!-- /.container-fluid -->

  </div>
</div>
<!-- /.row -->
