
        <div class="row">
          <div class="col-md-12">
            <?php if ($this->pageCount): ?>
            <ul class="pagination">
                <?php if (isset($this->previous)): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?php echo $this->url($this->route, array('action' => 'index', 'search_by' => $this->search_by, 'page' => $this->previous)); ?>">
                            <<
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            <<
                        </a>
                    </li>
                <?php endif; ?>
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li class="page-item">
                            <a class="page-link" href="<?php echo $this->url($this->route, array('action' => 'index', 'search_by' => $this->search_by, 'page' => $page)); ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="page-item active">
                            <a class="page-link" href="#"><?php echo $page; ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if (isset($this->next)): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?php echo $this->url($this->route, array('action' => 'index', 'search_by' => $this->search_by, 'page' => $this->next)); ?>">
                            >>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            >>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
            <?php endif; ?>
            </div>
        </div>
