<?php if ($user = $this->identity()): ?>
  <!-- Hero Section -->
  <div class="container space-2 space-top-md-3 space-top-lg-3 space-bottom-lg-1">
    <div class="row justify-content-lg-between">
      <div class="col-lg-12 mb-7 mb-lg-0">
        <!-- Info -->
        <div class="mb-5">
          <h1 class="h2 font-weight-medium mb-3">Welcome <?php echo $this->user->getFirstName(); ?> <?php echo $this->user->getLastName(); ?></h1>
        </div>
        <!-- End Info -->

        <?php
          $flash = $this->flashMessenger();
          $flash->setMessageOpenFormat('<div%s role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              ')
              ->setMessageSeparatorString('')
              ->setMessageCloseString('</div>');

          echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
          echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
          echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
          echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
           ?>
      </div>
    </div>
  </div>
  <!-- End Hero Section -->

  <!-- Call to Action Section -->
  <div class="container">
    <div class="row mb-4">
      <div class="col-md-8">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
      </div>
      <div class="col-md-4">
        <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('project', array('action' => 'create',)); ?>">Create A Project</a>
      </div>
    </div>
  </div>
<?php else: ?>
  <!-- Hero Section -->
  <div class="container space-2 space-top-md-3 space-top-lg-3 space-bottom-lg-1">
    <div class="row justify-content-lg-between mb-7">
      <div class="col-lg-5 mb-7 mb-lg-0">
        <!-- Info -->
        <div class="mb-5">
          <h1 class="h2 font-weight-medium mb-3">Welcome to BlockStarter. Start your business.</h1>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
        </div>
        <div class="mb-3">
          <a class="btn btn-primary btn-wide transition-3d-hover mb-2 mb-sm-0 mr-3" href="#">Get Started</a>
          <a class="btn btn-outline-primary btn-wide transition-3d-hover mb-2 mb-sm-0" href="#">Let's Talk</a>
        </div>
        <!-- End Info -->
      </div>
      <div class="col-lg-6">
        <img class="img-fluid w-100 rounded" src="/img/splash.jpg" alt="">
      </div>
    </div>
  </div>
  <!-- End Hero Section -->

  <!-- Call to Action Section -->
  <div class="container">
    <div class="row mb-4">
      <div class="col-md-8">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
      </div>
      <div class="col-md-4">
        <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('registration'); ?>">Register</a>
      </div>
    </div>
  </div>
  <!-- SVG Top Shape -->
  <figure>
    <svg preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="64px"
         viewBox="0 0 1921 273" style="margin-bottom: -8px; enable-background:new 0 0 1921 273;" xml:space="preserve">
      <polygon class="fill-gray-100" points="0,273 1921,273 1921,0 "/>
    </svg>
  </figure>
  <!-- End SVG Top Shape -->
  <!-- Marketing Icons Section -->
  <div class="container space-1 space-lg-1">
    <div class="row">
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Project Transparency</h4>
          <div class="card-body">
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Learn More</a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Resource Management</h4>
          <div class="card-body">
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae atque exercitationem ut consequuntur, sed eveniet, magni nostrum sint fuga.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Learn More</a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Earn Incetives</h4>
          <div class="card-body">
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Learn More</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
<?php endif; ?>

<div id="learnSection" class="clearfix border-bottom">
  <div class="container">
    <!-- Title -->
    <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-9">
      <h2 class="h1 font-weight-normal">Open Projects</h2>
      <p>Start a project or be a contributor.</p>
    </div>
    <!-- End Title -->
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-12">
        <?php
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            "partial/home/paginator.phtml",
            array(
              'route' => 'projects',
              'search_by' => $this->search_by,
            )
        );
      ?>
        <?php foreach ($paginator as $row):
            if ($user = $this->identity()){
              $publicAddress = $this->user->getPublicAddress();
            }else{
              $publicAddress = $this->config['ethereum']['public_address'];
            }
            $projectAttributes = $this->getProjectAttributes($row->getContractAddress(), $publicAddress);
            // echo "<pre>";
            // print_r($projectAttributes);
            // echo "</pre>"; exit();
          ?>
          <article class="d-block card border-0 mb-7">
            <div class="card-body p-0">
              <div class="row">
                <div class="col-sm-5 mb-5 mb-sm-0">
                  <a href="<?php echo $this->url('project', array('action' => 'view', 'id' => $row->getContractAddress(),)); ?>"><img class="img-fluid w-100 rounded" src="/img/project/<?php echo $row->getId(); ?>/photo_480x320.jpg" alt="<?php echo $this->escapehtml($row->getName()); ?>"></a>
                </div>
                <div class="col-sm-7">
                  <div class="pr-4">
                    <div>
                      <h2 class="h5">
                        <a href="<?php echo $this->url('project', array('action' => 'view', 'id' => $row->getContractAddress(),)); ?>"><?php echo $this->escapehtml($row->getName()); ?></a>
                      </h2>
                      <p><?php echo $this->escapehtml($row->getDescription()); ?></p>
                      <p>Minimum Contribution: ETH <?php echo $this->escapehtml($row->getMinimumContribution()); ?></p>
                    </div>
                    <small class="d-block text-secondary">Contract Address: <a class="text-dark font-weight-semi-bold" href="#"><?php echo $this->escapehtml($row->getContractAddress()); ?></a></small>
                  </div>
                  <br>
                  <div class="row mb-1">
                    <div class="col-6">
                      <h4 class="small text-muted">
                        Milestones: <strong class="text-secondary"> <?php echo $projectAttributes['milestonesCount']; ?></strong>
                      </h4>
                      <div class="js-hr-progress progress" style="height: 6px;">
                        <div class="js-hr-progress-bar progress-bar bg-success" role="progressbar" style="width: <?php echo $projectAttributes['milestonesCount']; ?>%;" aria-valuenow="<?php echo $projectAttributes['milestonesCount']; ?>" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                    <div class="col-6">
                      <h4 class="small text-muted">
                        Contributors: <strong class="text-secondary"><?php echo $projectAttributes['contributorsCount']; ?></strong>
                      </h4>
                      <div class="js-hr-progress progress" style="height: 6px;">
                        <div class="js-hr-progress-bar progress-bar bg-warning" role="progressbar" style="width: <?php echo $projectAttributes['contributorsCount']; ?>%;" aria-valuenow="<?php echo $projectAttributes['contributorsCount']; ?>" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                  <br><a class="btn btn-primary" href="<?php echo $this->url('project', array('action' => 'view', 'id' => $row->getContractAddress(),)); ?>">View Project</a>

                </div>
              </div>
            </div>
          </article>

        <?php endforeach; ?>

        <?php
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            "partial/home/paginator.phtml",
            array(
              'route' => 'projects',
              'search_by' => $this->search_by,
            )
        );
      ?>
    </div>
    <!-- Sidebar Widgets Column -->
  </div>
</div>

<!-- /.row -->

<?php if (!$user = $this->identity()): ?>
  <!-- Testimonials Section -->
  <div class="container space-bottom-1">
    <!-- SVG Quote -->
    <figure class="mx-auto text-center mb-3">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="48px" height="48px"
         viewBox="0 0 8 8" style="enable-background:new 0 0 8 8;" xml:space="preserve">
        <path class="fill-gray-400" d="M3,1.3C2,1.7,1.2,2.7,1.2,3.6c0,0.2,0,0.4,0.1,0.5c0.2-0.2,0.5-0.3,0.9-0.3c0.8,0,1.5,0.6,1.5,1.5c0,0.9-0.7,1.5-1.5,1.5
          C1.4,6.9,1,6.6,0.7,6.1C0.4,5.6,0.3,4.9,0.3,4.5c0-1.6,0.8-2.9,2.5-3.7L3,1.3z M7.1,1.3c-1,0.4-1.8,1.4-1.8,2.3
          c0,0.2,0,0.4,0.1,0.5c0.2-0.2,0.5-0.3,0.9-0.3c0.8,0,1.5,0.6,1.5,1.5c0,0.9-0.7,1.5-1.5,1.5c-0.7,0-1.1-0.3-1.4-0.8
          C4.4,5.6,4.4,4.9,4.4,4.5c0-1.6,0.8-2.9,2.5-3.7L7.1,1.3z"/>
      </svg>
    </figure>
    <!-- End SVG Quote -->

    <!-- Blockquote -->
    <div class="w-md-75 text-center mx-md-auto mb-6">
      <blockquote class="lead font-weight-normal">The biggest barrier to starting a company isn't ideas, funding, or experiences. It's excuses.</blockquote>
    </div>
    <!-- End Blockquote -->

    <!-- Reviewer -->
    <div class="d-flex justify-content-center align-items-center w-lg-50 mx-auto">
      <div class="u-avatar">
        <img class="img-fluid rounded-circle" src="/img/mik.jpg" alt="Image Description">
      </div>
      <div class="ml-3">
        <h4 class="h6 mb-0">Mik Galon</h4>
        <small class="text-muted">BlockStarter Team Lead</small>
      </div>
    </div>
    <!-- End Reviewer -->
  </div>
  <!-- End Testimonials Section -->

  <!-- SVG Top Shape -->
  <figure>
    <svg preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="64px"
         viewBox="0 0 1921 273" style="margin-bottom: -8px; enable-background:new 0 0 1921 273;" xml:space="preserve">
      <polygon class="fill-gray-100" points="0,273 1921,273 1921,0 "/>
    </svg>
  </figure>
  <!-- End SVG Top Shape -->
<?php endif; ?>
